### ISSUE TITLE
ReadMe needs to be updated to show usage and installation

### ISSUE THREAD

**Issue by jrolstad** [lrosenman/ambient#5]
The ReadMe contents need to be updated so that it shows a simple sample usage of the package and how to install the package in a project.

**Comment by lrosenman** [comment]
Can you re-do this pull?  I did the merges in the wrong order :( 

sorry

**Comment by jrolstad** [comment]
@lrosenman sure thing.  I just re-submitted as PR #12

**Comment by lrosenman** [comment]
Thanks, Merged.
